In [1]:
import numpy as np

In [3]:
array1 = np.array([[10, 20, 30, 40]])

In [10]:
array2 = np.zeros((5,8)); array2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
array2 = np.ones((3,5)); array2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
array3= np.linspace(2, 5, 8); array3

array([2.        , 2.42857143, 2.85714286, 3.28571429, 3.71428571,
       4.14285714, 4.57142857, 5.        ])

In [15]:
array4 = np.eye(4); array4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
array5 = np.diag((1,2,3,4,5)); array5

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [21]:
np.random.seed(42)

In [22]:
array6 = np.random.rand(5);array6

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [23]:
array6 = np.random.randn(5);array6

array([ 0.27904129,  1.01051528, -0.58087813, -0.52516981, -0.57138017])